-- DROP SCHEMA dbo;

CREATE SCHEMA dbo;
-- GAMEREC.dbo.GAME definition

-- Drop table

-- DROP TABLE GAMEREC.dbo.GAME GO

CREATE TABLE GAMEREC.dbo.GAME (
	GAME_ID int NOT NULL,
	NAM varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DESC] varchar(8000) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	IMG varchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT GAME_PK PRIMARY KEY (GAME_ID)
) GO;


-- GAMEREC.dbo.GENRE definition

-- Drop table

-- DROP TABLE GAMEREC.dbo.GENRE GO

CREATE TABLE GAMEREC.dbo.GENRE (
	GENRE_ID int NOT NULL,
	NAM varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	CONSTRAINT GENRE_PK PRIMARY KEY (GENRE_ID)
) GO;


-- GAMEREC.dbo.USR definition

-- Drop table

-- DROP TABLE GAMEREC.dbo.USR GO

CREATE TABLE GAMEREC.dbo.USR (
	USR_ID int IDENTITY(0,1) NOT NULL,
	USR_UUID uniqueidentifier NOT NULL,
	CONSTRAINT USR_PK PRIMARY KEY (USR_ID)
) GO;


-- GAMEREC.dbo.GAME_GENRE_XREF definition

-- Drop table

-- DROP TABLE GAMEREC.dbo.GAME_GENRE_XREF GO

CREATE TABLE GAMEREC.dbo.GAME_GENRE_XREF (
	GAME_ID int NOT NULL,
	GENRE_ID int NOT NULL,
	CONSTRAINT GAME_GENRE_XREF_PK PRIMARY KEY (GAME_ID,GENRE_ID),
	CONSTRAINT GAME_GENRE_XREF_FK FOREIGN KEY (GAME_ID) REFERENCES GAMEREC.dbo.GAME(GAME_ID),
	CONSTRAINT GAME_GENRE_XREF_FK1 FOREIGN KEY (GENRE_ID) REFERENCES GAMEREC.dbo.GENRE(GENRE_ID)
) GO;


-- GAMEREC.dbo.USR_GAME definition

-- Drop table

-- DROP TABLE GAMEREC.dbo.USR_GAME GO

CREATE TABLE GAMEREC.dbo.USR_GAME (
	USR_ID int NOT NULL,
	GAME_ID int NOT NULL,
	CONSTRAINT USR_GAME_PK PRIMARY KEY (USR_ID,GAME_ID),
	CONSTRAINT USR_GAME_FK FOREIGN KEY (USR_ID) REFERENCES GAMEREC.dbo.USR(USR_ID),
	CONSTRAINT USR_GAME_FK1 FOREIGN KEY (GAME_ID) REFERENCES GAMEREC.dbo.GAME(GAME_ID)
) GO;


-- GAMEREC.dbo.USR_RECOM definition

-- Drop table

-- DROP TABLE GAMEREC.dbo.USR_RECOM GO

CREATE TABLE GAMEREC.dbo.USR_RECOM (
	USR_ID int NOT NULL,
	GAME_ID int NOT NULL,
	CONSTRAINT USR_RECOM_PK PRIMARY KEY (USR_ID,GAME_ID),
	CONSTRAINT USR_RECOM_FK FOREIGN KEY (USR_ID) REFERENCES GAMEREC.dbo.USR(USR_ID),
	CONSTRAINT USR_RECOM_FK1 FOREIGN KEY (GAME_ID) REFERENCES GAMEREC.dbo.GAME(GAME_ID)
) GO;

