server:
  port: 8080
  servlet:
    context-path: /game-rec
spring:
  datasource:
    url: jdbc:sqlserver://gamerec.database.windows.net:1433;databaseName=GAMEREC
    username: adminGR
    password: '!passw0rd'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: false
      maximum-pool-size: 50
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database: SQL_SERVER
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 30
        cache:
          use_second_level_cache: false
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
  jta:
    enabled: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      
application:
  gamespot-url: https://www.gamespot.com/api/
  gamespot-api-key: b80d38c5b85ff1d323c7c9b4be4cba1adae0b80b 